version: '2'
services:
 app:
  image: nginx
  container_name: proxyserver
  volumes:
   - /media/james/pi-ssd/share_files/Websites/reverseproxy:/usr/share/nginx/html
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=lucinda.branconet.com
   - NGINX_PORT=80