version: '2'
services:
 app:
  image: nginx
  container_name: webserver1
  volumes:
   - /media/james/pi-ssd/share_files/Websites/lucinda-art-gallery:/usr/share/nginx/html
   - /media/james/pi-ssd/container-program-files/ngnix/webserver1:/etc/
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=lucinda.branconet.com
   - NGINX_PORT=80