version: '2'
services:
 app:
  image: nginx
  container_name: ws1-branconet.com
  volumes:
   - /home/james/container-program-files/branconet.com:/usr/share/nginx/html
  #  - /media/james/pi-ssd/container-program-files/Websites/webserver1/config:/etc/nginx/conf.d
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=branconet.com
   - NGINX_PORT=80